import { useEffect, useState } from "react";
import { api, fileUrl } from "../../api/axios";
import ConfirmModal from "../../components/ConfirmModal";
import Toast from "../../components/Toast";

const blankService={name:"",description:"",longDescription:"",estimatedDuration:"",priceRange:"",groupId:"",includedItems:"",benefits:"",isFeatured:false,isActive:true,images:[]};
const blankGroup={name:"",description:"",sortOrder:0,isActive:true};
const lines=value=>{try{return JSON.parse(value||"[]").join("\n")}catch{return""}};
const apiMessage=error=>error.response?.data?.message||"The request could not be completed";
const coverFallbacks={"Oil Change":"/images/oil-change.jpg","Full Service":"/images/full-service.jpg","Engine Diagnosis":"/images/engine-diagnosis.jpg","Brake Inspection":"/images/brake-inspection.jpg","Wheel Alignment":"/images/wheel-alignment.jpg","Battery Check":"/images/battery-check.jpg","Car Wash & Detailing":"/images/detailing.jpg"};
const imageError=file=>!file?"Choose an image file.":!(["image/jpeg","image/png","image/webp"].includes(file.type)||/\.(jpe?g|png|webp)$/i.test(file.name))?"Use a JPG, PNG or WebP image.":file.size>5*1024*1024?"Image must be 5MB or smaller.":"";

export default function ServicesManage(){
  const[tab,setTab]=useState("services"),[items,setItems]=useState([]),[groups,setGroups]=useState([]),[form,setForm]=useState(blankService),[edit,setEdit]=useState(),[cover,setCover]=useState(),[coverPreview,setCoverPreview]=useState(""),[galleryFiles,setGalleryFiles]=useState([]),[galleryPreviews,setGalleryPreviews]=useState([]),[groupForm,setGroupForm]=useState(blankGroup),[groupEdit,setGroupEdit]=useState(),[remove,setRemove]=useState(),[errors,setErrors]=useState({}),[groupErrors,setGroupErrors]=useState({}),[toast,setToast]=useState(),[busy,setBusy]=useState(false);
  const load=()=>Promise.all([api.get("/services"),api.get("/services/groups")]).then(([services,categories])=>{setItems(services.data);setGroups(categories.data)}).catch(error=>setToast({type:"error",message:apiMessage(error)}));
  useEffect(()=>{load()},[]);
  useEffect(()=>{
    if(!edit){setCoverPreview("");return}
    if(!cover){setCoverPreview(edit.imageUrl?fileUrl(edit.imageUrl):coverFallbacks[edit.name]||"/images/full-service.jpg");return}
    const reader=new FileReader();
    reader.onload=()=>setCoverPreview(String(reader.result||""));
    reader.onerror=()=>setErrors(current=>({...current,image:"This image could not be previewed. Choose another file."}));
    reader.readAsDataURL(cover);
    return()=>{reader.onload=null;reader.onerror=null};
  },[cover,edit]);
  const fieldError=key=>errors[key]&&<small className="field-error">{Array.isArray(errors[key])?errors[key][0]:errors[key]}</small>;
  const groupError=key=>groupErrors[key]&&<small className="field-error">{Array.isArray(groupErrors[key])?groupErrors[key][0]:groupErrors[key]}</small>;
  const change=(key,value)=>{setForm(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:undefined}))};
  const openService=service=>{setEdit(service||{});setForm(service?{...service,groupId:service.groupId||"",includedItems:lines(service.includedItems),benefits:lines(service.benefits),images:service.images||[]}:blankService);setCover();setGalleryFiles([]);setGalleryPreviews([]);setErrors({})};
  const chooseCover=file=>{if(!file)return;const message=imageError(file);if(message)return setErrors(current=>({...current,image:message}));setCover(file);setErrors(current=>({...current,image:undefined}))};
  const chooseGallery=async files=>{const selected=[...files],bad=selected.find(file=>imageError(file));if(bad)return setErrors(current=>({...current,gallery:imageError(bad)}));const remaining=10-(form.images?.length||0);if(selected.length>Math.min(8,remaining))return setErrors(current=>({...current,gallery:`Choose no more than ${Math.min(8,remaining)} additional images.`}));const previews=await Promise.all(selected.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,url:String(reader.result||"")});reader.onerror=reject;reader.readAsDataURL(file)}))).catch(()=>null);if(!previews)return setErrors(current=>({...current,gallery:"One or more selected images could not be previewed."}));setGalleryFiles(selected);setGalleryPreviews(previews);setErrors(current=>({...current,gallery:undefined}))};
  const removePendingGallery=index=>{setGalleryFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index));setGalleryPreviews(current=>current.filter((_,itemIndex)=>itemIndex!==index))};
  const saveService=async event=>{event.preventDefault();const local={};if(form.name.trim().length<2)local.name="Enter at least 2 characters.";if(form.description.trim().length<10)local.description="Enter at least 10 characters.";if(Object.keys(local).length)return setErrors(local);setBusy(true);setErrors({});const data=new FormData();Object.entries(form).filter(([key])=>key!=="images"&&key!=="group").forEach(([key,value])=>data.append(key,value??""));if(cover)data.append("image",cover);try{const response=edit.id?await api.put(`/services/${edit.id}`,data):await api.post("/services",data);if(galleryFiles.length){const gallery=new FormData();galleryFiles.forEach(file=>gallery.append("images",file));await api.post(`/services/${response.data.id}/images`,gallery)}setToast({type:"success",message:edit.id?"Service page updated":"Service page created"});setEdit();await load()}catch(error){setErrors(error.response?.data?.errors||{});setToast({type:"error",message:apiMessage(error)})}finally{setBusy(false)}};
  const removeCover=async()=>{try{await api.delete(`/services/${edit.id}/cover`);setEdit(current=>({...current,imageUrl:null}));setCover();setToast({type:"success",message:"Cover image deleted from the server"});await load()}catch(error){setToast({type:"error",message:apiMessage(error)})}};
  const deleteGalleryImage=async image=>{try{await api.delete(`/services/${edit.id}/images/${image.id}`);setForm(current=>({...current,images:current.images.filter(item=>item.id!==image.id)}));setToast({type:"success",message:"Gallery image deleted from the server"})}catch(error){setToast({type:"error",message:apiMessage(error)})}};
  const moveImage=async(index,direction)=>{const next=[...form.images],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setForm(current=>({...current,images:next}));try{await api.put(`/services/${edit.id}/images/order`,{imageIds:next.map(image=>image.id)})}catch(error){setToast({type:"error",message:apiMessage(error)})}};
  const openGroup=group=>{setGroupEdit(group||{});setGroupForm(group?{name:group.name,description:group.description||"",sortOrder:group.sortOrder,isActive:group.isActive}:blankGroup);setGroupErrors({})};
  const saveGroup=async event=>{event.preventDefault();if(groupForm.name.trim().length<2)return setGroupErrors({name:"Enter at least 2 characters."});setBusy(true);setGroupErrors({});try{groupEdit?.id?await api.put(`/services/groups/${groupEdit.id}`,groupForm):await api.post("/services/groups",groupForm);setToast({type:"success",message:groupEdit?.id?"Category updated":"Category created"});setGroupEdit();setGroupForm(blankGroup);await load()}catch(error){setGroupErrors(error.response?.data?.errors||{});setToast({type:"error",message:apiMessage(error)})}finally{setBusy(false)}};
  const del=async()=>{try{remove.type==="group"?await api.delete(`/services/groups/${remove.item.id}`):await api.delete(`/services/${remove.item.id}`);setToast({type:"success",message:`${remove.type==="group"?"Category":"Service"} deleted`});setRemove();await load()}catch(error){setToast({type:"error",message:apiMessage(error)});setRemove()}};
  return <div className="admin-content">
    {toast&&<Toast type={toast.type} message={toast.message} onClose={()=>setToast()}/>}
    {tab==="services"?<div className="admin-title"><div><span className="kicker">SERVICE CATALOGUE</span><h1>Service categories</h1><p>Control which services customers can view and book.</p></div><div className="admin-title-actions"><button className="btn ghost" onClick={()=>setTab("categories")}><i className="fa-solid fa-folder-tree"/> Manage categories</button><button className="btn" onClick={()=>openService()}><i className="fa-solid fa-plus"/> Add service</button></div></div>:<div className="admin-title"><div><span className="kicker">SERVICE CATALOGUE</span><h1>Manage categories</h1><p>Organise services without changing the main catalogue layout.</p></div><div className="admin-title-actions"><button className="btn ghost" onClick={()=>setTab("services")}><i className="fa-solid fa-arrow-left"/> Back to services</button><button className="btn" onClick={()=>openGroup()}><i className="fa-solid fa-plus"/> Add category</button></div></div>}
    {tab==="services"?<div className="manage-grid">{items.map(service=><article className="manage-card" key={service.id}>{service.imageUrl?<img src={fileUrl(service.imageUrl)} alt=""/>:<div className="service-placeholder"><i className="fa-solid fa-screwdriver-wrench"/></div>}<div><div className="manage-head"><h3>{service.name}</h3><span className={`badge ${service.isActive?"completed":"rejected"}`}>{service.isActive?"Active":"Inactive"}</span></div><p>{service.description}</p><small><i className="fa-regular fa-clock"/> {service.estimatedDuration||"—"} · {service.priceRange||"—"}</small><div className="card-actions"><button onClick={()=>openService(service)}><i className="fa-solid fa-pen"/> Edit</button><button className="red" onClick={()=>setRemove({type:"service",item:service})}><i className="fa-solid fa-trash"/> Delete</button></div></div></article>)}</div>
    :<div className="category-admin-grid">{groups.map(group=><article className="admin-panel category-admin-card" key={group.id}><div><span className="category-order">{group.sortOrder}</span><div><h3>{group.name}</h3><p>{group.description||"No description"}</p></div></div><div className="category-card-footer"><span>{group._count.services} service{group._count.services===1?"":"s"} · {group.isActive?"Visible":"Hidden"}</span><div><button onClick={()=>openGroup(group)}>Edit</button><button className="red" onClick={()=>setRemove({type:"group",item:group})}>Delete</button></div></div></article>)}</div>}
    {edit&&<div className="modal-backdrop"><form className="modal service-modal service-page-editor" onSubmit={saveService} noValidate>
      <button type="button" className="modal-close" onClick={()=>setEdit()} aria-label="Close"><i className="fa-solid fa-xmark"/></button><span className="kicker">SERVICE PAGE</span><h2>{edit.id?"Edit service page":"Create service page"}</h2>
      <div className="editor-section"><h3>Catalogue information</h3><div className="form-grid"><label>Name *<input value={form.name} maxLength="80" aria-invalid={!!errors.name} onChange={e=>change("name",e.target.value)}/>{fieldError("name")}</label><label>Category<select value={form.groupId} onChange={e=>change("groupId",e.target.value)}><option value="">Uncategorized</option>{groups.map(group=><option value={group.id} key={group.id}>{group.name}</option>)}</select></label><label className="wide">Card summary *<textarea rows="3" maxLength="1000" value={form.description} aria-invalid={!!errors.description} onChange={e=>change("description",e.target.value)}/>{fieldError("description")}</label><label className="wide">Full detail-page description<textarea rows="6" maxLength="6000" value={form.longDescription||""} onChange={e=>change("longDescription",e.target.value)}/></label><label>Estimated duration<input value={form.estimatedDuration||""} onChange={e=>change("estimatedDuration",e.target.value)}/></label><label>Price range<input value={form.priceRange||""} onChange={e=>change("priceRange",e.target.value)}/></label><label>Typical inclusions (one per line)<textarea rows="6" value={form.includedItems||""} onChange={e=>change("includedItems",e.target.value)}/></label><label>Customer benefits (one per line)<textarea rows="6" value={form.benefits||""} onChange={e=>change("benefits",e.target.value)}/></label></div></div>
      <div className="editor-section"><h3>Card cover image</h3>{coverPreview&&<div className="existing-cover-preview"><img src={coverPreview} alt="Service cover preview" onError={event=>{event.currentTarget.src=coverFallbacks[edit.name]||"/images/full-service.jpg"}}/><div><strong>{cover?"New cover preview":edit.imageUrl?"Current cover image":"Default cover image"}</strong><small>{cover?"Save the service to upload this replacement.":edit.imageUrl?"Stored on the server and used publicly.":"Built-in fallback; upload an image to replace it."}</small>{edit.id&&edit.imageUrl&&!cover&&<button type="button" className="cover-delete-btn" onClick={removeCover}><i className="fa-solid fa-trash"/> Delete cover</button>}{cover&&<button type="button" className="cover-delete-btn neutral" onClick={()=>setCover()}><i className="fa-solid fa-rotate-left"/> Cancel replacement</button>}</div></div>}<label className="wide upload-box"><i className="fa-solid fa-image"/><span>{cover?.name||"Upload or replace the catalogue cover"}</span><small>JPG, PNG or WebP · maximum 5MB</small><input hidden type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>{chooseCover(e.target.files[0]);e.target.value=""}}/></label>{fieldError("image")}</div>
      <div className="editor-section service-gallery-admin"><div className="gallery-admin-head"><div><h3>Detail-page gallery</h3><p>Upload up to 10 supporting images. Use arrows to control their order.</p></div><label className="btn ghost btn-sm"><i className="fa-solid fa-images"/> Choose images<input hidden multiple type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>{chooseGallery(e.target.files);e.target.value=""}}/></label></div>{fieldError("gallery")}{galleryPreviews.length>0&&<div className="pending-image-grid">{galleryPreviews.map((preview,index)=><article key={`${preview.name}-${index}`}><img src={preview.url} alt={`Preview of ${preview.name}`}/><div><small>{preview.name}</small><button type="button" onClick={()=>removePendingGallery(index)} aria-label={`Remove selected image ${preview.name}`}><i className="fa-solid fa-xmark"/></button></div></article>)}</div>}{form.images?.length>0?<div className="admin-gallery-grid">{form.images.map((image,index)=><article key={image.id}><img src={fileUrl(image.imageUrl)} alt={image.altText||""}/><div><button type="button" disabled={index===0} onClick={()=>moveImage(index,-1)} aria-label="Move image left"><i className="fa-solid fa-arrow-left"/></button><span>{index+1}</span><button type="button" disabled={index===form.images.length-1} onClick={()=>moveImage(index,1)} aria-label="Move image right"><i className="fa-solid fa-arrow-right"/></button><button type="button" className="red" onClick={()=>deleteGalleryImage(image)} aria-label="Remove gallery image"><i className="fa-solid fa-trash"/></button></div></article>)}</div>:<div className="gallery-empty"><i className="fa-regular fa-images"/><span>No supporting images yet.</span></div>}</div>
      <div className="form-grid toggle-grid"><label className="check-line"><input type="checkbox" checked={form.isFeatured} onChange={e=>change("isFeatured",e.target.checked)}/> Feature on homepage</label><label className="check-line"><input type="checkbox" checked={form.isActive} onChange={e=>change("isActive",e.target.checked)}/> Public and bookable</label></div>
      <div className="modal-actions sticky-actions"><button type="button" className="btn ghost" onClick={()=>setEdit()}>Cancel</button><button className="btn" disabled={busy}>{busy?"Saving…":"Save complete service page"}</button></div>
    </form></div>}
    {groupEdit&&<div className="modal-backdrop"><form className="modal" onSubmit={saveGroup} noValidate><button type="button" className="modal-close" onClick={()=>setGroupEdit()} aria-label="Close"><i className="fa-solid fa-xmark"/></button><span className="kicker">CATALOGUE CATEGORY</span><h2>{groupEdit.id?"Edit category":"Add category"}</h2><label>Name *<input value={groupForm.name} onChange={e=>setGroupForm({...groupForm,name:e.target.value})}/>{groupError("name")}</label><label>Description<textarea rows="4" maxLength="500" value={groupForm.description} onChange={e=>setGroupForm({...groupForm,description:e.target.value})}/>{groupError("description")}</label><label>Display order<input type="number" min="0" max="999" value={groupForm.sortOrder} onChange={e=>setGroupForm({...groupForm,sortOrder:Number(e.target.value)})}/>{groupError("sortOrder")}</label><label className="check-line"><input type="checkbox" checked={groupForm.isActive} onChange={e=>setGroupForm({...groupForm,isActive:e.target.checked})}/> Show category publicly</label><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setGroupEdit()}>Cancel</button><button className="btn" disabled={busy}>{busy?"Saving…":"Save category"}</button></div></form></div>}
    {remove&&<ConfirmModal title={`Delete ${remove.type}?`} message={remove.type==="group"?"Move or remove the services in this category first.":"Services with booking history must be hidden instead of deleted."} danger confirmText="Delete" onClose={()=>setRemove()} onConfirm={del}/>}
  </div>
}
