import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "react-toastify/dist/ReactToastify.css";
import "./styles/global.css";
import "./styles/public-enhancements.css";
import "./styles/deployment-ready.css";
import "./styles/cms.css";
import "./styles/premium.css";
import "./styles/qa-fixes.css";
import "./styles/feature-fixes.css";
import "./styles/service-cover.css";
import "./styles/services-classic.css";
import "./styles/image-preview-fixes.css";
import "./styles/editorial-heroes.css";
import "./styles/messages.css";
import "./styles/toast.css";
import "./styles/toastify-theme.css";
createRoot(document.getElementById("root")).render(<StrictMode><App/></StrictMode>);
